# Build a product recommendation engine

![](https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/doc/source/images/shopping.png)

This notebook contains steps and code to create a recommendation engine based on shopping history, deploy that model to Watson Machine Learning, and create an app with PixieApps. This notebook runs on Python 3.x with Apache Spark 2.1.

## Learning Goals

The learning goals of this notebook are:

* Load a CSV file into the Object Storage service linked to your Watson Studio
* Use the *k*-means algorithm, which is useful for cluster analysis in data mining, to segment customers into clusters for the purpose of making an in-store purchase recommendation
* Deploy the model to the IBM Watson Machine Learning service in IBM Cloud to create your recommendation application

## Table of contents

1. [Setup](#setup)<br>
2. [Load and explore data](#load)<br>
3. [Create a KMeans model](#kmeans)<br>
   3.1. [Prepare data](#prepare_data)<br>
   3.2. [Create clusters and define the model](#build_model)<br>
4. [Persist the model](#persist)<br>
5. [Deploy the model to the cloud](#deploy)<br>
   5.1. [Create deployment for the model](#create_deploy)<br>
   5.2. [Test model deployment](#test_deploy)<br>
6. [Create product recommendations](#create_recomm)<br>
   6.1. [Test product recommendations model](#test_recomm)<br>
7. [Summary and next steps](#summary)<br>

## 1. Setup


Before you use the sample code in this notebook, you must perform the following setup tasks:

* Create a Watson Machine Learning service instance (a free plan is offered) and associate it with your project

We'll be using a few libraries for this exercise:

1. [Watson Machine Learning Client](http://wml-api-pyclient.mybluemix.net/): Client library to work with the Watson Machine Learning service on IBM Cloud. Library available on [pypi](https://pypi.org/project/watson-machine-learning-client/). Service available on [IBM Cloud](https://cloud.ibm.com/catalog/services/machine-learning).
1. [Pixiedust](https://github.com/pixiedust/pixiedust): Python Helper library for Jupyter Notebooks. Available on [pypi](https://pypi.org/project/pixiedust/).
1. [ibmos2spark](https://github.com/ibm-watson-data-lab/ibmos2spark): Facilitates Data I/O between Spark and IBM Object Storage services

In [1]:
!pip install --upgrade ibmos2spark
!pip install --upgrade pixiedust
!pip install --upgrade watson-machine-learning-client

Waiting for a Spark session to start...
Spark Initialization Done! ApplicationId = app-20191102111211-0000
KERNEL_ID = 268c13d5-5e8c-4ed4-a363-f3650d30c86d
Collecting ibmos2spark
  Downloading https://files.pythonhosted.org/packages/c6/81/1edb24382edef1ca636e87972b2da286b8271a586c728a21f916d3cd76cd/ibmos2spark-1.0.1-py2.py3-none-any.whl
Installing collected packages: ibmos2spark
Successfully installed ibmos2spark-1.0.1
Collecting pixiedust
  Downloading https://files.pythonhosted.org/packages/bc/a8/e84b2ed12ee387589c099734b6f914a520e1fef2733c955982623080e813/pixiedust-1.1.17.tar.gz (197kB)
    100% |################################| 204kB 4.2MB/s eta 0:00:01
Collecting mpld3 (from pixiedust)
  Downloading https://files.pythonhosted.org/packages/91/95/a52d3a83d0a29ba0d6898f6727e9858fe7a43f6c2ce81a5fe7e05f0f4912/mpld3-0.3.tar.gz (788kB)
    100% |################################| 798kB 4.0MB/s eta 0:00:01
Collecting lxml (from pixiedust)
  Downloading https://files.pythonhosted.org/packages/ec/be/5ab8abdd8663c0386ec2dd595a5bc0e23330a0549b8a91e32f38c20845b6/lxml-4.4.1-cp36-cp36m-manylinux1_x86_64.whl (5.8MB)
    100% |################################| 5.8MB 2.3MB/s eta 0:00:01
Collecting geojson (from pixiedust)
  Downloading https://files.pythonhosted.org/packages/e4/8d/9e28e9af95739e6d2d2f8d4bef0b3432da40b7c3588fbad4298c1be09e48/geojson-2.5.0-py2.py3-none-any.whl
Collecting astunparse (from pixiedust)
  Downloading https://files.pythonhosted.org/packages/2e/37/5dd0dd89b87bb5f0f32a7e775458412c52d78f230ab8d0c65df6aabc4479/astunparse-1.6.2-py2.py3-none-any.whl
Collecting markdown (from pixiedust)
  Downloading https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl (87kB)
    100% |################################| 92kB 5.0MB/s eta 0:00:01
Collecting colour (from pixiedust)
  Downloading https://files.pythonhosted.org/packages/74/46/e81907704ab203206769dee1385dc77e1407576ff8f50a0681d0a6b541be/colour-0.1.5-py2.py3-none-any.whl
Collecting requests (from pixiedust)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |################################| 61kB 3.0MB/s eta 0:00:01
Collecting six<2.0,>=1.6.1 (from astunparse->pixiedust)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting wheel<1.0,>=0.23.0 (from astunparse->pixiedust)
  Downloading https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
Collecting setuptools>=36 (from markdown->pixiedust)
  Downloading https://files.pythonhosted.org/packages/d9/de/554b6310ac87c5b921bc45634b07b11394fe63bc4cb5176f5240addf18ab/setuptools-41.6.0-py2.py3-none-any.whl (582kB)
    100% |################################| 583kB 4.6MB/s eta 0:00:01
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->pixiedust)
  Downloading https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl (125kB)
    100% |################################| 133kB 4.7MB/s eta 0:00:01
Collecting certifi>=2017.4.17 (from requests->pixiedust)
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
    100% |################################| 163kB 4.9MB/s eta 0:00:01
Collecting chardet<3.1.0,>=3.0.2 (from requests->pixiedust)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 5.5MB/s eta 0:00:01
Collecting idna<2.9,>=2.5 (from requests->pixiedust)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |################################| 61kB 3.4MB/s eta 0:00:01
Building wheels for collected packages: pixiedust, mpld3
  Building wheel for pixiedust (setup.py) ... done
  Stored in directory: /home/spark/shared/.cache/pip/wheels/25/fa/a5/09c1e8f4c91b34c5f7f4ac6e41be81dd0667030a2372546a8d
  Building wheel for mpld3 (setup.py) ... done
  Stored in directory: /home/spark/shared/.cache/pip/wheels/c0/47/fb/8a64f89aecfe0059830479308ad42d62e898a3e3cefdf6ba28
Successfully built pixiedust mpld3
tensorflow 1.13.1 requires tensorboard<1.14.0,>=1.13.0, which is not installed.
ibm-cos-sdk-core 2.4.3 has requirement urllib3<1.25,>=1.20, but you'll have urllib3 1.25.6 which is incompatible.
botocore 1.12.82 has requirement urllib3<1.25,>=1.20, but you'll have urllib3 1.25.6 which is incompatible.
Installing collected packages: mpld3, lxml, geojson, six, wheel, astunparse, setuptools, markdown, colour, urllib3, certifi, chardet, idna, requests, pixiedust
Successfully installed astunparse-1.6.2 certifi-2019.9.11 chardet-3.0.4 colour-0.1.5 geojson-2.5.0 idna-2.8 lxml-4.4.1 markdown-3.1.1 mpld3-0.3 pixiedust-1.1.17 requests-2.22.0 setuptools-41.6.0 six-1.12.0 urllib3-1.25.6 wheel-0.33.6
Collecting watson-machine-learning-client
  Downloading https://files.pythonhosted.org/packages/ac/5c/be0d3efe27704bbd43481b7de364ade8c686e867617caba8654989e0864b/watson_machine_learning_client-1.0.375-py3-none-any.whl (536kB)
    100% |################################| 542kB 4.7MB/s eta 0:00:01
Collecting certifi (from watson-machine-learning-client)
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting ibm-cos-sdk (from watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/dc/e8/a23b8ac15771c11d2a3324acf0086958101d9383fc9c9f0eea9b4b6f6fce/ibm-cos-sdk-2.5.5.tar.gz (53kB)
    100% |################################| 61kB 3.6MB/s eta 0:00:01
Collecting requests (from watson-machine-learning-client)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting tabulate (from watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/66/d4/977fdd5186b7cdbb7c43a7aac7c5e4e0337a84cb802e154616f3cfc84563/tabulate-0.8.5.tar.gz (45kB)
    100% |################################| 51kB 3.4MB/s eta 0:00:01
Collecting lomond (from watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/0f/b1/02eebed49c754b01b17de7705caa8c4ceecfb4f926cdafc220c863584360/lomond-0.3.3-py2.py3-none-any.whl
Collecting urllib3 (from watson-machine-learning-client)
  Using cached https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl
Collecting pandas (from watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/52/3f/f6a428599e0d4497e1595030965b5ba455fd8ade6e977e3c819973c4b41d/pandas-0.25.3-cp36-cp36m-manylinux1_x86_64.whl (10.4MB)
    100% |################################| 10.4MB 1.6MB/s eta 0:00:01
Collecting tqdm (from watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/05/f2/764a5d530cf143ded9bc95216edb6e258c6554511e78de7c250557e8f3ed/tqdm-4.37.0-py2.py3-none-any.whl (53kB)
    100% |################################| 61kB 2.8MB/s eta 0:00:01
Collecting ibm-cos-sdk-core==2.5.5 (from ibm-cos-sdk->watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/76/ca/4a641809181c591ebc4b749d790422ebb7b528f6e99ffcb805ca04706681/ibm-cos-sdk-core-2.5.5.tar.gz (751kB)
    100% |################################| 757kB 4.9MB/s eta 0:00:01

Collecting ibm-cos-sdk-s3transfer==2.5.5 (from ibm-cos-sdk->watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/ec/6c/f44a3384964e45aebb0df4211e0bbdd02552a1445fb9ca7b21e2e54e4c60/ibm-cos-sdk-s3transfer-2.5.5.tar.gz (221kB)
    100% |################################| 225kB 5.4MB/s eta 0:00:01
Collecting jmespath<1.0.0,>=0.7.1 (from ibm-cos-sdk->watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->watson-machine-learning-client)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->watson-machine-learning-client)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting six>=1.10.0 (from lomond->watson-machine-learning-client)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting numpy>=1.13.3 (from pandas->watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/0e/46/ae6773894f7eacf53308086287897ec568eac9768918d913d5b9d366c5db/numpy-1.17.3-cp36-cp36m-manylinux1_x86_64.whl (20.0MB)
    100% |################################| 20.0MB 1.1MB/s eta 0:00:01
Collecting python-dateutil>=2.6.1 (from pandas->watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |################################| 235kB 5.6MB/s eta 0:00:01
Collecting pytz>=2017.2 (from pandas->watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
    100% |################################| 512kB 5.4MB/s eta 0:00:01
Collecting docutils<0.16,>=0.10 (from ibm-cos-sdk-core==2.5.5->ibm-cos-sdk->watson-machine-learning-client)
  Downloading https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl (547kB)
    100% |################################| 552kB 5.1MB/s eta 0:00:01
Building wheels for collected packages: ibm-cos-sdk, tabulate, ibm-cos-sdk-core, ibm-cos-sdk-s3transfer
  Building wheel for ibm-cos-sdk (setup.py) ... done
  Stored in directory: /home/spark/shared/.cache/pip/wheels/4b/d1/47/7bfbd0c47216fbf180dd8e39df62499f26e0ef94100b5feb62
  Building wheel for tabulate (setup.py) ... done
  Stored in directory: /home/spark/shared/.cache/pip/wheels/e1/41/5e/e201f95d90fc84f93aa629b6638adacda680fe63aac47174ab
  Building wheel for ibm-cos-sdk-core (setup.py) ... done
  Stored in directory: /home/spark/shared/.cache/pip/wheels/0e/f5/95/9c4a7d23860dc34fe0a49f2265b5259802d2ad72156fd9a6fe
  Building wheel for ibm-cos-sdk-s3transfer (setup.py) ... done
  Stored in directory: /home/spark/shared/.cache/pip/wheels/e9/80/1a/6bdcf3777571ab7a36539a65f0fc95c13d347a7162f32bd5ce
Successfully built ibm-cos-sdk tabulate ibm-cos-sdk-core ibm-cos-sdk-s3transfer
tensorflow 1.13.1 requires tensorboard<1.14.0,>=1.13.0, which is not installed.
botocore 1.12.82 has requirement urllib3<1.25,>=1.20, but you'll have urllib3 1.25.6 which is incompatible.
Installing collected packages: certifi, jmespath, docutils, chardet, urllib3, idna, requests, six, python-dateutil, ibm-cos-sdk-core, ibm-cos-sdk-s3transfer, ibm-cos-sdk, tabulate, lomond, numpy, pytz, pandas, tqdm, watson-machine-learning-client
Successfully installed certifi-2019.9.11 chardet-3.0.4 docutils-0.15.2 ibm-cos-sdk-2.5.5 ibm-cos-sdk-core-2.5.5 ibm-cos-sdk-s3transfer-2.5.5 idna-2.8 jmespath-0.9.4 lomond-0.3.3 numpy-1.17.3 pandas-0.25.3 python-dateutil-2.8.0 pytz-2019.3 requests-2.22.0 six-1.12.0 tabulate-0.8.5 tqdm-4.37.0 urllib3-1.25.6 watson-machine-learning-client-1.0.375

In [2]:
import pixiedust

Pixiedust database opened successfully
Table VERSION_TRACKER created successfully
Table METRICS_TRACKER created successfully

Share anonymous install statistics? (opt-out instructions)

PixieDust will record metadata on its environment the next time the package is installed or updated. The data is anonymized and aggregated to help plan for future releases, and records only the following values:

{
   "data_sent": currentDate,
   "runtime": "python",
   "application_version": currentPixiedustVersion,
   "space_id": nonIdentifyingUniqueId,
   "config": {
       "repository_id": "https://github.com/ibm-watson-data-lab/pixiedust",
       "target_runtimes": ["Data Science Experience"],
       "event_id": "web",
       "event_organizer": "dev-journeys"
   }
}
You can opt out by calling pixiedust.optOut() in a new cell.

Pixiedust runtime updated. Please restart kernel
Table SPARK_PACKAGES created successfully
Table USER_PREFERENCES created successfully
Table service_connections created successfully

<a id="load"></a>
## 2. Load and explore data

In this section you will load the data file that contains the customer shopping data using PixieDust's [`sampleData`](https://pixiedust.github.io/pixiedust/loaddata.html) method:

In [3]:
df = pixiedust.sampleData('https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/data/customers_orders1_opt.csv')

Downloading 'https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/data/customers_orders1_opt.csv' from https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/data/customers_orders1_opt.csv
Downloaded 5648773 bytes
Creating pySpark DataFrame for 'https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/data/customers_orders1_opt.csv'. Please wait...
Loading file using 'SparkSession'
Successfully created pySpark DataFrame for 'https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/data/customers_orders1_opt.csv'

To better examine and visualize the data, run the following cell to view it in a table format. Note that Pixiedust's `display` method can also render data using various chart types, such as pie charts, line graphs, and scatter plots.

In [4]:
display(df)

<a id="kmeans"></a>
## 3. Create a *k*-means model with Spark

In this section of the notebook you use the *k*-means implementation to associate every customer to a cluster based on their shopping history.

First, import the Apache Spark Machine Learning packages ([MLlib](http://spark.apache.org/docs/2.2.0/api/python/pyspark.ml.html)) that you need in the subsequent steps:

In [5]:
from pyspark.ml import Pipeline
from pyspark.ml.clustering import KMeans
from pyspark.ml.clustering import KMeansModel
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.linalg import Vectors

<a id="prepare_data"></a>
### 3.1 Prepare data

Create a new data set with just the data that you need. Filter the columns that you want, in this case the customer ID column and the product-related columns. Remove the columns that you don't need for aggregating the data and training the model:

In [6]:
# Here are the product cols. In a real world scenario we would query a product table, or similar.
product_cols = ['Baby Food', 'Diapers', 'Formula', 'Lotion', 'Baby wash', 'Wipes', 'Fresh Fruits', 'Fresh Vegetables', 'Beer', 'Wine', 'Club Soda', 'Sports Drink', 'Chips', 'Popcorn', 'Oatmeal', 'Medicines', 'Canned Foods', 'Cigarettes', 'Cheese', 'Cleaning Products', 'Condiments', 'Frozen Foods', 'Kitchen Items', 'Meat', 'Office Supplies', 'Personal Care', 'Pet Supplies', 'Sea Food', 'Spices']
# Here we get the customer ID and the products they purchased
df_filtered = df.select(['CUST_ID'] + product_cols)

Run the `display()` command again, this time to view the filtered information:

In [7]:
display(df_filtered)

Now, aggregate the individual transactions for each customer to get a single score per product, per customer.

In [8]:
df_customer_products = df_filtered.groupby('CUST_ID').sum()  # Use customer IDs to group transactions by customer and sum them up
df_customer_products = df_customer_products.drop('sum(CUST_ID)')
display(df_customer_products)

<a id="build_model"></a>
### 3.2 Create clusters and define the model 

Create 100 clusters with a *k*-means model based on the number of times a specific customer purchased a product.

| No Clustering | Clustering |
|------|------|
|  ![](https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/doc/source/images/kmeans-1.jpg)  | ![](https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/doc/source/images/kmeans-2.jpg) |

First, create a feature vector by combining the product and quantity columns:

In [9]:
assembler = VectorAssembler(inputCols=["sum({})".format(x) for x in product_cols],outputCol="features") # Assemble vectors using product fields

Next, create the *k*-means clusters and the pipeline to define the model:

In [10]:
kmeans = KMeans(maxIter=50, predictionCol="cluster").setK(100).setSeed(1)  # Initialize model
pipeline = Pipeline(stages=[assembler, kmeans])
model = pipeline.fit(df_customer_products)

Finally, calculate the cluster for each customer by running the original dataset against the *k*-means model:

In [11]:
df_customer_products_cluster = model.transform(df_customer_products)
display(df_customer_products_cluster)

<a id="persist"></a>
## 4. Persist the model 

In this section you will learn how to store your pipeline and model in Watson Machine Learning repository by using Python client libraries.

### 4.1 Configure IBM Watson Machine Learning credentials

To access your machine learning repository programmatically, you need to copy in your credentials, which you can see in your **IBM Watson Machine Learning** service details in IBM Cloud.

> **IMPORTANT**: Update `apikey` and `instance_id` below. Credentials can be found on _Service Credentials_ tab of the Watson Machine Learning service instance created on the IBM Cloud.

In [14]:
# @hidden_cell
wml_credentials = {
  "apikey": "qzzOjtgqranQAxVDtP5LRKIYtiLYzKHIdAgCl3y8Ko-n",
  "iam_apikey_description": "Auto-generated for key 98b7d26f-c2ed-4470-b38b-b06846575452",
  "iam_apikey_name": "wdp-writer",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/35ca09a55a9948909cc9d5cf74084c20::serviceid:ServiceId-c105c041-3365-4279-93c1-bbc17a1e6615",
  "instance_id": "77d02a8b-b331-4866-861a-002ae3cf9f3f",
  "url": "https://us-south.ml.cloud.ibm.com"
}

print(wml_credentials)

{'apikey': 'qzzOjtgqranQAxVDtP5LRKIYtiLYzKHIdAgCl3y8Ko-n', 'iam_apikey_description': 'Auto-generated for key 98b7d26f-c2ed-4470-b38b-b06846575452', 'iam_apikey_name': 'wdp-writer', 'iam_role_crn': 'crn:v1:bluemix:public:iam::::serviceRole:Writer', 'iam_serviceid_crn': 'crn:v1:bluemix:public:iam-identity::a/35ca09a55a9948909cc9d5cf74084c20::serviceid:ServiceId-c105c041-3365-4279-93c1-bbc17a1e6615', 'instance_id': '77d02a8b-b331-4866-861a-002ae3cf9f3f', 'url': 'https://us-south.ml.cloud.ibm.com'}

Connect to the Watson Machine Learning service using the provided credentials.

In [15]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient
client = WatsonMachineLearningAPIClient(wml_credentials)
print(client.version)

1.0.375

### 4.2 Save the model 

#### Save the model to the Watson Machine Learning repository

You use the Watson Machine Learning client's [Repository class](http://wml-api-pyclient.mybluemix.net/#repository) to store and manage models in the Watson Machine Learning service. 

> **NOTE**: You can also use Watson Studio to manage models. In this notebook we are using the client library instead.

In [16]:
train_data = df_customer_products.withColumnRenamed('CUST_ID', 'label')

> **TIP**: Update the cell below with your name, email, and name you wish to give to your model.

In [17]:
model_props = {client.repository.ModelMetaNames.AUTHOR_NAME: "IBM", 
               client.repository.ModelMetaNames.NAME: "Shopping Recommendation Engine"}
published_model = client.repository.store_model(model=model, pipeline=pipeline, meta_props=model_props, training_data=train_data)

> **NOTE**: You can delete a model from the repository by calling `client.repository.delete`.

#### Display list of existing models in the Watson Machine Learning repository

In [18]:
client.repository.list_models()

------------------------------------  ------------------------------  ------------------------  ---------
GUID                                  NAME                            CREATED                   FRAMEWORK
e6d39c3a-1f5c-4d84-9efb-70c90d8a032a  Shopping Recommendation Engine  2019-11-02T11:21:49.594Z  mllib-2.3
------------------------------------  ------------------------------  ------------------------  ---------

#### Display information about the saved model

In [19]:
import json
saved_model_uid = client.repository.get_model_uid(published_model)
model_details = client.repository.get_details(saved_model_uid)
print(json.dumps(model_details, indent=2))

{
  "metadata": {
    "guid": "e6d39c3a-1f5c-4d84-9efb-70c90d8a032a",
    "url": "https://us-south.ml.cloud.ibm.com/v3/wml_instances/77d02a8b-b331-4866-861a-002ae3cf9f3f/published_models/e6d39c3a-1f5c-4d84-9efb-70c90d8a032a",
    "created_at": "2019-11-02T11:21:49.594Z",
    "modified_at": "2019-11-02T11:21:49.662Z"
  },
  "entity": {
    "runtime_environment": "spark-2.3",
    "learning_configuration_url": "https://us-south.ml.cloud.ibm.com/v3/wml_instances/77d02a8b-b331-4866-861a-002ae3cf9f3f/published_models/e6d39c3a-1f5c-4d84-9efb-70c90d8a032a/learning_configuration",
    "author": {
      "name": "IBM"
    },
    "name": "Shopping Recommendation Engine",
    "label_col": "label",
    "learning_iterations_url": "https://us-south.ml.cloud.ibm.com/v3/wml_instances/77d02a8b-b331-4866-861a-002ae3cf9f3f/published_models/e6d39c3a-1f5c-4d84-9efb-70c90d8a032a/learning_iterations",
    "training_data_schema": {
      "fields": [
        {
          "metadata": {
            "modeling_role": "target"
          },
          "name": "label",
          "nullable": true,
          "type": "integer"
        },
        {
          "metadata": {},
          "name": "sum(Baby Food)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Diapers)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Formula)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Lotion)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Baby wash)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Wipes)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Fresh Fruits)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Fresh Vegetables)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Beer)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Wine)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Club Soda)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Sports Drink)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Chips)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Popcorn)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Oatmeal)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Medicines)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Canned Foods)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Cigarettes)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Cheese)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Cleaning Products)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Condiments)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Frozen Foods)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Kitchen Items)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Meat)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Office Supplies)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Personal Care)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Pet Supplies)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Sea Food)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Spices)",
          "nullable": true,
          "type": "long"
        }
      ],
      "type": "struct"
    },
    "feedback_url": "https://us-south.ml.cloud.ibm.com/v3/wml_instances/77d02a8b-b331-4866-861a-002ae3cf9f3f/published_models/e6d39c3a-1f5c-4d84-9efb-70c90d8a032a/feedback",
    "latest_version": {
      "url": "https://us-south.ml.cloud.ibm.com/v3/ml_assets/models/e6d39c3a-1f5c-4d84-9efb-70c90d8a032a/versions/8896bb7e-94f9-46f8-9d5d-e026d72935cf",
      "guid": "8896bb7e-94f9-46f8-9d5d-e026d72935cf",
      "created_at": "2019-11-02T11:21:49.662Z"
    },
    "model_type": "mllib-2.3",
    "deployments": {
      "count": 0,
      "url": "https://us-south.ml.cloud.ibm.com/v3/wml_instances/77d02a8b-b331-4866-861a-002ae3cf9f3f/published_models/e6d39c3a-1f5c-4d84-9efb-70c90d8a032a/deployments"
    },
    "evaluation_metrics_url": "https://us-south.ml.cloud.ibm.com/v3/wml_instances/77d02a8b-b331-4866-861a-002ae3cf9f3f/published_models/e6d39c3a-1f5c-4d84-9efb-70c90d8a032a/evaluation_metrics",
    "input_data_schema": {
      "fields": [
        {
          "metadata": {},
          "name": "sum(Baby Food)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Diapers)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Formula)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Lotion)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Baby wash)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Wipes)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Fresh Fruits)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Fresh Vegetables)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Beer)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Wine)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Club Soda)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Sports Drink)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Chips)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Popcorn)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Oatmeal)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Medicines)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Canned Foods)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Cigarettes)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Cheese)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Cleaning Products)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Condiments)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Frozen Foods)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Kitchen Items)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Meat)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Office Supplies)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Personal Care)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Pet Supplies)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Sea Food)",
          "nullable": true,
          "type": "long"
        },
        {
          "metadata": {},
          "name": "sum(Spices)",
          "nullable": true,
          "type": "long"
        }
      ],
      "type": "struct"
    }
  }
}

<a id="deploy"></a>
## 5. Deploy model to the IBM cloud

You use the Watson Machine Learning client's [Deployments class](http://wml-api-pyclient.mybluemix.net/#deployments) to deploy and score models.

### 5.1 Create an online deployment for the model

In [20]:
created_deployment = client.deployments.create(saved_model_uid, 'Shopping Recommendation Engine Deployment')

#######################################################################################

Synchronous deployment creation for uid: 'e6d39c3a-1f5c-4d84-9efb-70c90d8a032a' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='6caa573a-02ca-460f-9b81-c53dc567c495'
------------------------------------------------------------------------------------------------

### 5.2 Retrieve the scoring endpoint for this model

In [21]:
scoring_endpoint = client.deployments.get_scoring_url(created_deployment)
print(scoring_endpoint)

https://us-south.ml.cloud.ibm.com/v3/wml_instances/77d02a8b-b331-4866-861a-002ae3cf9f3f/deployments/6caa573a-02ca-460f-9b81-c53dc567c495/online

<a id="test_deploy"></a>
### 5.3 Test the deployed model

To verify that the model was successfully deployed to the cloud, you'll specify a customer ID, for example customer 12027, to predict this customer's cluster against the Watson Machine Learning deployment, and see if it matches the cluster that was previously associated this customer ID.

In [22]:
customer = df_customer_products_cluster.filter('CUST_ID = 12027').collect()
print("Previously calculated cluster = {}".format(customer[0].cluster))

Previously calculated cluster = 9

To determine the customer's cluster using Watson Machine Learning, you need to load the customer's purchase history. This function uses the local data frame to select every product field and the number of times that customer 12027 purchased a product.

In [23]:
from six import iteritems
def get_product_counts_for_customer(cust_id):
    cust = df_customer_products.filter('CUST_ID = {}'.format(cust_id)).take(1)
    fields = []
    values = []
    for row in cust:
        for product_col in product_cols:
            field = 'sum({})'.format(product_col)
            value = row[field]
            fields.append(field)
            values.append(value)
    return (fields, values)

This function takes the customer's purchase history and calls the scoring endpoint:

In [24]:
def get_cluster_from_watson_ml(fields, values):
    scoring_payload = {'fields': fields, 'values': [values]}
    predictions = client.deployments.score(scoring_endpoint, scoring_payload)   
    return predictions['values'][0][len(product_cols)+1]

Finally, call the functions defined above to get the product history, call the scoring endpoint, and get the cluster associated to customer 12027:

In [25]:
product_counts = get_product_counts_for_customer(12027)
fields = product_counts[0]
values = product_counts[1]
print("Cluster calculated by Watson ML = {}".format(get_cluster_from_watson_ml(fields, values)))

Cluster calculated by Watson ML = 9

<a id="create_recomm"></a>
## 6. Create product recommendations

Now you can create some product recommendations.

First, run this cell to create a function that queries the database and finds the most popular items for a cluster. In this case, the **df_customer_products_cluster** dataframe is the database.

In [26]:
# This function gets the most popular clusters in the cell by grouping by the cluster column
def get_popular_products_in_cluster(cluster):
    df_cluster_products = df_customer_products_cluster.filter('cluster = {}'.format(cluster))
    df_cluster_products_agg = df_cluster_products.groupby('cluster').sum()
    row = df_cluster_products_agg.rdd.collect()[0]
    items = []
    for product_col in product_cols:
        field = 'sum(sum({}))'.format(product_col)
        items.append((product_col, row[field]))
    sortedItems = sorted(items, key=lambda x: x[1], reverse=True) # Sort by score
    popular = [x for x in sortedItems if x[1] > 0]
    return popular

Now, run this cell to create a function that will calculate the recommendations based on a given cluster. This function finds the most popular products in the cluster, filters out products already purchased by the customer or currently in the customer's shopping cart, and finally produces a list of recommended products.

In [27]:
# This function takes a cluster and the quantity of every product already purchased or in the user's cart
from pyspark.sql.functions import desc
def get_recommendations_by_cluster(cluster, purchased_quantities):
    # Existing customer products
    print('PRODUCTS ALREADY PURCHASED/IN CART:')
    customer_products = []
    for i in range(0, len(product_cols)):
        if purchased_quantities[i] > 0:
            customer_products.append((product_cols[i], purchased_quantities[i]))
    df_customer_products = sc.parallelize(customer_products).toDF(["PRODUCT","COUNT"])
    df_customer_products.show()
    # Get popular products in the cluster
    print('POPULAR PRODUCTS IN CLUSTER:')
    cluster_products = get_popular_products_in_cluster(cluster)
    df_cluster_products = sc.parallelize(cluster_products).toDF(["PRODUCT","COUNT"])
    df_cluster_products.show()
    # Filter out products the user has already purchased
    print('RECOMMENDED PRODUCTS:')
    df_recommended_products = df_cluster_products.alias('cl').join(df_customer_products.alias('cu'), df_cluster_products['PRODUCT'] == df_customer_products['PRODUCT'], 'leftouter')
    df_recommended_products = df_recommended_products.filter('cu.PRODUCT IS NULL').select('cl.PRODUCT','cl.COUNT').sort(desc('cl.COUNT'))
    df_recommended_products.show(10)

Next, run this cell to create a function that produces a list of recommended items based on the products and quantities in a user's cart. This function uses Watson Machine Learning to calculate the cluster based on the shopping cart contents and then calls the **get_recommendations_by_cluster** function.

In [28]:
# This function would be used to find recommendations based on the products and quantities in a user's cart
def get_recommendations_for_shopping_cart(products, quantities):
    fields = []
    values = []
    for product_col in product_cols:
        field = 'sum({})'.format(product_col)
        if product_col in products:
            value = quantities[products.index(product_col)]
        else:
            value = 0
        fields.append(field)
        values.append(value)
    return get_recommendations_by_cluster(get_cluster_from_watson_ml(fields, values), values)

Run this cell to create a function that produces a list of recommended items based on the purchase history of a customer. This function uses Watson Machine Learning to calculate the cluster based on the customer's purchase history and then calls the **get_recommendations_by_cluster** function.

In [29]:
# This function is used to find recommendations based on the purchase history of a customer
def get_recommendations_for_customer_purchase_history(customer_id):
    product_counts = get_product_counts_for_customer(customer_id)
    fields = product_counts[0]
    values = product_counts[1]
    return get_recommendations_by_cluster(get_cluster_from_watson_ml(fields, values), values)

Now you can take customer 12027 and produce a recommendation based on that customer's purchase history:

In [30]:
get_recommendations_for_customer_purchase_history(12027)

PRODUCTS ALREADY PURCHASED/IN CART:
+-------------+-----+
|      PRODUCT|COUNT|
+-------------+-----+
|      Diapers|    1|
|    Baby wash|    1|
|         Beer|    1|
|         Wine|    3|
|    Medicines|    3|
|       Cheese|    3|
| Frozen Foods|    1|
|Kitchen Items|    1|
|     Sea Food|    1|
|       Spices|    2|
+-------------+-----+

POPULAR PRODUCTS IN CLUSTER:
+-----------------+-----+
|          PRODUCT|COUNT|
+-----------------+-----+
|           Cheese|   76|
|             Wine|   65|
|        Medicines|   63|
|         Sea Food|   42|
|     Frozen Foods|   38|
|           Spices|   31|
|    Personal Care|   23|
|       Cigarettes|   16|
|          Diapers|   15|
|       Condiments|   15|
|          Oatmeal|   12|
|     Canned Foods|   10|
|  Office Supplies|    9|
|        Baby Food|    8|
|           Lotion|    7|
|        Baby wash|    7|
|Cleaning Products|    7|
|    Kitchen Items|    7|
|             Beer|    6|
| Fresh Vegetables|    5|
+-----------------+-----+
only showing top 20 rows

RECOMMENDED PRODUCTS:
+-----------------+-----+
|          PRODUCT|COUNT|
+-----------------+-----+
|    Personal Care|   23|
|       Cigarettes|   16|
|       Condiments|   15|
|          Oatmeal|   12|
|     Canned Foods|   10|
|  Office Supplies|    9|
|        Baby Food|    8|
|           Lotion|    7|
|Cleaning Products|    7|
| Fresh Vegetables|    5|
+-----------------+-----+
only showing top 10 rows

Now, take a sample shopping cart and produce a recommendation based on the items in the cart:

In [31]:
get_recommendations_for_shopping_cart(['Diapers','Baby wash','Oatmeal'],[1,2,1])

PRODUCTS ALREADY PURCHASED/IN CART:
+---------+-----+
|  PRODUCT|COUNT|
+---------+-----+
|  Diapers|    1|
|Baby wash|    2|
|  Oatmeal|    1|
+---------+-----+

POPULAR PRODUCTS IN CLUSTER:
+-----------------+-----+
|          PRODUCT|COUNT|
+-----------------+-----+
|          Popcorn|  182|
|        Club Soda|  172|
|          Diapers|   47|
|     Sports Drink|   47|
| Fresh Vegetables|   42|
|        Baby Food|   38|
|          Formula|   36|
|            Wipes|   36|
|     Fresh Fruits|   34|
|    Kitchen Items|   32|
|           Lotion|   31|
|          Oatmeal|   31|
|             Beer|   29|
|  Office Supplies|   28|
|        Baby wash|   25|
|Cleaning Products|   13|
|       Condiments|    9|
+-----------------+-----+

RECOMMENDED PRODUCTS:
+----------------+-----+
|         PRODUCT|COUNT|
+----------------+-----+
|         Popcorn|  182|
|       Club Soda|  172|
|    Sports Drink|   47|
|Fresh Vegetables|   42|
|       Baby Food|   38|
|           Wipes|   36|
|         Formula|   36|
|    Fresh Fruits|   34|
|   Kitchen Items|   32|
|          Lotion|   31|
+----------------+-----+
only showing top 10 rows

The next optional section outlines how you can easily expose recommendations to notebook users, for example for test purposes.

<a id="test_recomm"></a>
### 6.1 Test product recommendations model

You can interactively test your product recommendations model using a simple PixieApp. [PixieApps](https://pixiedust.github.io/pixiedust/pixieapps.html) encapsulate business logic and data visualizations, making it easy for notebook users to explore data without having to write any code. Typically these applications are pre-packaged and imported into a notebook. However, for illustrative purposes we've embedded the product recommendation source code in this notebook.

![](https://raw.githubusercontent.com/IBM/product-recommendation-with-watson-ml/master/doc/source/images/product_recommendation_app.png")

Run the cell below, add items to the shopping cart and click the _Refresh_ button to review the recommendation results.

In [ ]:
# This function takes a cluster and the quantity of every product already purchased or in the user's cart & returns the data frame of recommendations for the PixieApp
from pyspark.sql.functions import desc
def get_recommendations_by_cluster_app(cluster, purchased_quantities):
    # Existing customer products
    customer_products = []
    for i in range(0, len(product_cols)):
        if purchased_quantities[i] > 0:
            customer_products.append((product_cols[i], purchased_quantities[i]))
    df_customer_products = sc.parallelize(customer_products).toDF(["PRODUCT","COUNT"])
    # Get popular products in the cluster
    cluster_products = get_popular_products_in_cluster(cluster)
    df_cluster_products = sc.parallelize(cluster_products).toDF(["PRODUCT","COUNT"])
    # Filter out products the user has already purchased
    df_recommended_products = df_cluster_products.alias('cl').join(df_customer_products.alias('cu'), df_cluster_products['PRODUCT'] == df_customer_products['PRODUCT'], 'leftouter')
    df_recommended_products = df_recommended_products.filter('cu.PRODUCT IS NULL').select('cl.PRODUCT','cl.COUNT').sort(desc('cl.COUNT'))
    return df_recommended_products


# PixieDust sample application

from pixiedust.display.app import *

@PixieApp
class RecommenderPixieApp:
    def setup(self):
        self.product_cols = product_cols
        
    def computeUserRecs(self, shoppingcart):   
        #format products and quantities from shopping cart display data
        lst = list(zip(*[(item.split(":")[0],int(item.split(":")[1])) for item in shoppingcart.split(",")]))
        products = list(lst[0])
        quantities = list(lst[1])
        #format for the Model function
        lst = list(zip(*[('sum({})'.format(item),quantities[products.index(item)] if item in products else 0) for item in self.product_cols]))
        fields = list(lst[0])
        values = list(lst[1])
        #call the run Model function
        recommendations_df = get_recommendations_by_cluster_app(get_cluster_from_watson_ml(fields, values), values)
        recs = [row["PRODUCT"] for row in recommendations_df.rdd.collect()]
        return recs[:5]
    
    @route(shoppingCart="*")
    def _recommendation(self, shoppingCart):
        recommendation = self.computeUserRecs(shoppingCart)
        self._addHTMLTemplateString(
        """
        <table style="width:100%"> {% for item in recommendation %} <tr> <td type="text" style="text-align:left">{{item}}</td> </tr> {% endfor %} </table>
        """, recommendation = recommendation)

        
    @route()
    def main(self):
        return """
        <script>
        function getValuesRec(){
            return $( "input[id^='prod']" )
            .filter(function( index ) {
                return parseInt($(this).val()) > 0;})
            .map(function(i, product) {
                return $(product).attr("name") + ":" + $(product).val();
            }).toArray().join(",");}
            
        function getValuesCart(){
            return $( "input[id^='prod']" )
            .filter(function( index ) {
                return parseInt($(this).val()) > 0; })
            .map(function(i, product) {
                return $(product).attr("name") + ":" + $(product).val();
            }).toArray(); }
        
        function populateCart(field) {
            user_cart = getValuesCart();
            $("#user_cart{{prefix}}").html("");
            if (user_cart.length > 0) {
                for (var i in user_cart) {
                    var item = user_cart[i];
                    var item_arr = item.split(":")
                    $("#user_cart{{prefix}}").append('<tr><td style="text-align:left">'+item_arr[1]+" "+item_arr[0]+"</td></tr>"); } }
            else { $("#user_cart{{prefix}}").append('<tr><td style="text-align:left">'+ "Cart Empty" +"</td></tr>"); } }
        
        function increase_by_one(field) {
            nr = parseInt(document.getElementById(field).value);
            document.getElementById(field).value = nr + 1;
            populateCart(field); }
        
        function decrease_by_one(field) {
            nr = parseInt(document.getElementById(field).value);
            if (nr > 0) { if( (nr - 1) >= 0) { document.getElementById(field).value = nr - 1; } }
            populateCart(field); } 
        </script>
        
        <table> Products: {% for item in this.product_cols %}
            {% if loop.index0 is divisibleby 4 %} <tr> {% endif %}
                <div class="prod-quantity">
                <td class="col-md-3">{{item}}:</td><td><input size="2" id="prod{{loop.index}}{{prefix}}" class="prods" type="text" 
                    style="text-align:center" value="0" name="{{item}}" /></td>
                <td><button onclick="increase_by_one('prod{{loop.index}}{{prefix}}');">+</button></td>
                <td><button onclick="decrease_by_one('prod{{loop.index}}{{prefix}}');">-</button></td>
                </div>
            {% if ((not loop.first) and (loop.index0 % 4 == 3)) or (loop.last) %} </tr> {% endif %}
        {% endfor %} </table>
        
        <div class="row">
            <div class="col-sm-6"> Your Cart: </div>
            <div class="col-sm-6"> Your Recommendations: <button pd_options="shoppingCart=$val(getValuesRec)" pd_target="recs{{prefix}}"> 
                <pd_script type="preRun"> if (getValuesRec()==""){alert("Your cart is empty");return false;} return true;
                </pd_script>Refresh </button> 
            </div>
        </div>
        
        <div class="row">
        <div class="col-sm-3"> <table style="width:100%" id="user_cart{{prefix}}"> </table> </div> <div class="col-sm-3"> </div>
        <div class="col-sm-3" id="recs{{prefix}}" pd_loading_msg="Calling your model in Watson ML"></div> <div class="col-sm-3"> </div>
        </div>
        """
        
    

#run the app
RecommenderPixieApp().run(runInDialog='false')

## <font color=green>Congratulations</font>, you've sucessfully created a recommendation engine, deployed it to the Watson Machine Learning service, and created a PixieApp!

You can now switch to the Watson Machine Learning console to deploy the model and then test it in application, or continue within the notebook to deploy the model using the APIs.